[workspace]
channels = [
    "https://prefix.dev/pixi-build-backends",
    "https://prefix.dev/conda-forge",
]
platforms = ["linux-64"]
preview = ["pixi-build"]
requires-pixi = ">=0.48"

[dependencies]
conda-build = "*"

[package]
name = "freecad"
version = "1.1.0dev"
homepage = "https://freecad.org"
repository = "https://github.com/FreeCAD/FreeCAD"
description = "FreeCAD"

[package.build]
backend = { name = "conda-build", version = "*" }

[feature.freecad.dependencies]
freecad = { path = "." }

[feature.package.dependencies]
python = ">=3.11,<3.12"

[feature.package.tasks]
create_bundle = 'bash -c "cd $(bash scripts/get_os.bash) && bash create_bundle.sh"'

## Linux (x86-64)
[feature.package.target.linux-64.dependencies]
coreutils = "*"
xcb-util-cursor = "==0.1.5"  ## hack to address https://github.com/FreeCAD/FreeCAD/issues/26726

[environments]
default = ["freecad"]
package = ["package"]
